# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
destination: /srv/output

# Site Settings
title: "UK-India Workshop on Chemical Routes to Energy Storage, Energy Conversion and Fuel Production"
email: "d.kramer@soton.ac.uk"
description: "Workshop for early-career academics and researcher from the UK and India with interests in batteries, fuel cells, and renewable fuels"
baseurl: ""
url: "http://localhost:4000"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"


# Head
metaKeywords: "event, workshop, batteries, fuel cells, CO2 reduction, UK, India, Newton Fund"



# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/logistics/", text: "Logistics"}

bottomNavigationLinks:
 - {link: "/apply", text: "Apply for a Place"}

rightNavigationButtons:
 - {link: "/apply", text: "Apply for a Place"}

# Hero Block
heroImage: "hero3.jpg"
heroTitle: "Electrochemical Routes to <typeout>"
eventDate: "9-15 December 2018 - Bangalore (India)"
typeoutTextValues: '"", "Energy Storage", "Energy Conversion", "Fuel Production"'
typeoutFallback: "Energy and Fuel"
heroButtons:
 - {permalink: "/apply", text: "Apply for a place"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About"
aboutBlock:
 - {title: "Talks", image: "conference.jpg", text: "Participants share their research with each other in short sessions." }
 - {title: "Mentoring", image: "mentor.jpg", text: "Mentors will be around to coach you on everything from grant applications to career advice." }
 - {title: "Site visit", image: "sitevisit.jpg", text: "Have a look at Shell's R&D site in Bangalore." }
 - {title: "Social", image: "social.jpg", text: "Get to know each other and enjoy the Indian culture." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "30", specialCharacter: "+", info: "attendees", detail: "from the UK and India"}
 - {count: "4", specialCharacter: "", info: "days", detail: "of discussions and making friends"}
 - {count: "4", specialCharacter: "", info: "mentors", detail: "from from the UK and India"}
 - {count: "1", specialCharacter: "", info: "site visit", detail: "to Shell R&D facilties"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Mentors"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Jawaharlal Nehru Centre for Advanced Scientific Research"
eventLocationLink: "http://www.jncasr.ac.in"
eventStreetAddress: "Jakkur"
eventAddressLocality: "Bangalore"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "560 064"
eventAddressCountry: "India"
eventStartTime: "2018-12-09T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-12-15T20:00"
eventPlaceCoordinates: "13.0685438, 77.61087499999996"
mapCenterCoordinates: "13.0685438, 77.61087499999996"
mapMobileCenterCoordinates: "13.0685438, 77.61087499999996"
mapsAPIKey: AIzaSyAQjTCWu1N1uyeeFxJtD2yYx0ITTq78SR4

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_1.jpg"
venueSmallImage1: "venue_6.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_6.jpg"
venueMediumImage1: "venue_5.jpg"
venueMediumImage2: "venue_4.jpg"
venueTitle: "Jawaharlal Nehru Centre for Advanced Scientific Research"
venueFeatures: ["beautiful campus", "Located close to the airport"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "elchemroutes2018"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Organisers Block
organisersTitle: "Organisers"
organisersImage: organisers.jpg

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://xabmfmm6of.execute-api.eu-west-1.amazonaws.com/prod/subscribe"
subscribeInfo: "Registration will be open around end of April. Number of places are limited. Stay tuned!"
subscribeSuccess: "Great. We will be in touch shortly"
subscribeError: "Ups. Something went wrong. Shoot us an eMail."

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird Industry"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-04-01T10:00"
  validThrough: "2018-10-31T23:59"
 -
  name: "Last Chance Industry"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-11-01T00:00"
  validThrough: "2018-11-31T23:59"
  disabled: true
 -
  name: "Non-UK/India Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-04-01T10:00"
  validThrough: "2018-11-31T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}

footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.jncasr.ac.in/", text: "Jawaharlal Nehru Centre for Advanced Scientific Research"}
   - {link: "http://www.britishcouncil.org/", text: "British Council"}
   - {link: "http://www.newtonfund.ac.uk/", text: "Newton Fund"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:d.kramer@soton.ac.uk", text: "Denis Kramer"}


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "elchemroutes2018ua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "13.0685438, 77.61087499999996"
logisticsMapMobileCenterCoordinates: "13.0685438, 77.61087499999996"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Bangalore"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}

directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
